version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar ./erpapp-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/erp-app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Tolstochok3000

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "erp-app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Tolstochok3000"
    ports:
        - "5432:5432"
    restart: always